# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_layout = us
  kb_options = compose:ins # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 49
  repeat_delay = 220

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitity for mouse/trackpack (default: 0)
  sensitivity = -0.25
  accel_profile = flat
  force_no_accel = true


  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

cursor {
  no_hardware_cursors = true
  # no_warps = true                    # Prevents unwanted cursor position changes
  default_monitor = DP-1             # Set to your 144Hz primary monitor name
  enable_hyprcursor = true
  warp_on_change_workspace = 0
  use_cpu_buffer = true
}

# OpenGL fixes for NVIDIA
opengl {
  nvidia_anti_flicker = true
}

# Misc section - disable VRR for testing
misc {
  vrr = 0                            # Disable Variable Refresh Rate
  vfr = true
  initial_workspace_tracking = 0
}

# # Scroll nicely in the terminal
# windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)
# windowrule = scrolltouchpad 0.2, class:com.mitchellh.ghostty

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
# gesture = 3, horizontal, workspace
